[build-system]
requires = [
    "setuptools>=60",
    "setuptools-scm>=8.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "hera-cli-utils"
description = "HERA CLI Utils"
authors = [
    {name="Steven Murray", email="steven.murray@sns.it"}
]
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
]
requires-python = ">=3.9"
dependencies = [
    "click>=8",
    "rich",
    "psutil",
    "line-profiler",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/steven-murray/hera-cli-utils"
Documentation = "https://hera-cli-utils.readthedocs.io"
Changelog = "https://github.com/steven-murray/hera-cli-utils/releases"

[project.optional-dependencies]
docs = [
    "furo>=2021.11.12",
    "sphinx>=4.3.2",
    "sphinx-autobuild>=2021.3.14",
    "sphinx-click>=3.0.2",
    "myst-parser>=0.16.1",
]

tests = [
    "pytest>=6.2.5",
    "xdoctest[colors]>=0.15.10",
    "nox",
]

dev = [
    "hera-cli-utils[tests,docs]",
    "pre-commit",
]

[project.scripts]
hera-cli-utils = "hera_cli_utils.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["hera_cli_utils"]

[tool.coverage.report]
show_missing = true
fail_under = 70

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[tool.mypy]
strict = false
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
ignore_missing_imports = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
strict_equality = true
strict_concatenate = true
check_untyped_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true

# This one fails on types like `np.ndarray`
#disallow_any_generics = true

# These next few are various gradations of forcing use of type annotations
disallow_untyped_calls = false
disallow_incomplete_defs = true
disallow_untyped_defs = true

# This one isn't too hard to get passing, but return on investment is lower
no_implicit_reexport = true

# This one can be tricky to get passing if you use a lot of untyped libraries
warn_return_any = false
